apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: Swagger Petstore API
  annotations:
    backstage.io/api-lifecycle: experimental
    backstage.io/api-owner: group:default/team-c
    backstage.io/api-type: openapi
  links:
    - url: https://petstore.swagger.io
      title: Swagger UI
      icon: swagger
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition: |
    openapi: 3.0.0
    info:
      title: Swagger Petstore
      version: 1.0.0
    paths:
      /pets:
        get:
          summary: List all pets
          operationId: listPets
          responses:
            '200':
              description: A paged array of pets
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string

