apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: Swagger Petstore API
  owner: team-c
  lifecycle: experimental
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition: |
    openapi: 3.0.0
    info:
      title: Swagger Petstore
      version: 1.0.0
    servers:
      - url: https://petstore.swagger.io/v1
    paths:
      /pets:
        get:
          summary: List all pets
          responses:
            '200':
              description: A list of pets.
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string
        post:
          summary: Create a pet
          responses:
            '201':
              description: The created pet.

         

