apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: Swagger Petstore API
  owner: team-c
  lifecycle: experimental
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition: |
    openapi: 3.0.0
    info:
      title: Swagger Petstore
      version: 1.0.0
      description: A simple API to manage a petstore
      license:
        name: MIT
    servers:
      - url: https://petstore.swagger.io/v1
    paths:
      /pets:
        get:
          summary: List all pets
          operationId: listPets
          responses:
            '200':
              description: A paged array of pets
              content:
                application/json:    
                  schema:
                    $ref: '#/components/schemas/Pets'
        post:
          summary: Create a pet
          operationId: createPets
          responses:
            '201':
              description: Null response
    components:
      schemas:
        Pet:
          type: object
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            tag:
              type: string
        Pets:
          type: array
          items:
            $ref: '#/components/schemas/Pet'



         

