apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: Swagger Petstore API
  tags:
    - swagger
    - openapi
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition: 'https://petstore.swagger.io/v2/swagger.json'

