apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    gitlab.com/project-id: 60030582
spec:
  type: website
  lifecycle: production
  owner: user:guest
